apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: mykafka
  name: mykafka
spec:
  replicas: 1
  selector:
    app: mykafka
    deploymentconfig: mykafka
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: mykafka
        deploymentconfig: mykafka
    spec:
      containers:
        - env:
            - name: KAFKA_LOG_DIRS
              value: /kafka2
            - name: KAFKA_BROKER_ID
              value: '1'
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: mykafka
            - name: KAFKA_ADVERTISED_PORT
              value: '9092'
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: 'myzoo:2181'
          image: >-
            shlomoweiss/mykafka@sha256:c1d18063c14843b6b1e458153e0c14c619996f7ee7ca00cb46c4f89a6a2bf580
          imagePullPolicy: IfNotPresent
          name: mykafka
          ports:
            - containerPort: 9092
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /kafka
              name: mykafka-1
            - mountPath: /kafka2
              name: mykafka-2
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: mykafka-1
        - emptyDir: {}
          name: mykafka-2
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - mykafka
        from:
          kind: ImageStreamTag
          name: 'mykafka:1.0.2.0'
        lastTriggeredImage: >-
          shlomoweiss/mykafka@sha256:c1d18063c14843b6b1e458153e0c14c619996f7ee7ca00cb46c4f89a6a2bf580
      type: ImageChange
