apiVersion: v1
kind: Service
metadata:
  name: extkafka
  labels:
    name: extkafka
spec:
  externalIPs:
   - 192.168.1.45
   - 192.168.1.44
  type: NodePort
  ports:
    - port: 9092
      nodePort: 30036
      name: tcp
  selector:
    app: mykafka
    deploymentconfig: mykafka
